baseURL = "https://johndoe.dev"
languageCode = 'en-us'
title = 'Rajab Kabeer | Portfolio'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "Rajab Kabeer"
location = "Kerala, India"
description = "some description kinda thing"
profile_image = "/images/profile.jpg"
github = "https://github.com/Muhammed-Rajab"
github_username = "Muhammed-Rajab"
email = ""
instagram = "https://instagram.com/rajabkabeer"

[menu]
  [[menu.main]]
    name = "Blogs"
    url = "/blog"
    weight = 1



[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de"
