baseURL = "https://johndoe.dev"
languageCode = 'en-us'
title = 'Rajab Kabeer | Portfolio'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "Rajab Kabeer"
location = "Kerala, India"
description = "some description kinda thing"
profile_image = "/images/profile.jpg"
github = "https://github.com/Muhammed-Rajab"
github_username = "Muhammed-Rajab"
email = ""
instagram = "https://instagram.com/rajabkabeer"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de"

[menu]
  [[menu.main]]
    name = "Blogs"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "About me"
    url = "/about-me/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[languages.de.menu]
  [[languages.de.menu.main]]
    name = "Blog"  # German typically uses singular
    url = "/de/blog/"
    weight = 1
  [[languages.de.menu.main]]
    name = "Projekte"
    url = "/de/projects/"
    weight = 2
  [[languages.de.menu.main]]
    name = "Über mich"
    url = "/de/about/"
    weight = 3
  [[languages.de.menu.main]]
    name = "Kontakt"
    url = "/de/contact/"
    weight = 4
